# Generated by Django 3.1.4 on 2021-02-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://farrerpark.thegoodboys.com.sg/wp-content/uploads/2019/11/food-placeholder.jpg', max_length=500),
        ),
    ]
